#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tPa37.p1 
    set site_4_0 $site_4_0
    set site_5_0 $site_4_0.fra39
    set site_5_0 $site_4_0.scr40
    set site_4_1 .top37.tPa37.p2 
    set site_4_0 $site_4_1
    set site_5_0 $site_4_0.fra41
    set site_5_0 $site_4_0.scr45
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x550+387+131
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow.Label -background #d9d9d9
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font TkDefaultFont
    ttk::panedwindow $top.tPa37 \
        -width 200 -height 200 
    vTcl:DefineAlias "$top.tPa37" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa37.p1 \
        -text {Extract Text} -underline 8 -width 200 -height 200 
    vTcl:DefineAlias "$top.tPa37.p1" "extractTextTPane" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa37.p1
    frame $site_4_0.fra39 \
        -borderwidth 5 -relief groove -background {#d9d9d9} -height 75 \
        -highlightcolor black -width 225 
    vTcl:DefineAlias "$site_4_0.fra39" "imgPathFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra39
    ttk::label $site_5_0.tLa37 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text Path: 
    vTcl:DefineAlias "$site_5_0.tLa37" "pathTLabel" vTcl:WidgetProc "Toplevel1" 1
    text $site_5_0.tex38 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 10 \
        -wrap word 
    .top37.tPa37.p1.fra39.tex38 configure -font TkTextFont
    .top37.tPa37.p1.fra39.tex38 insert end text
    vTcl:DefineAlias "$site_5_0.tex38" "pathText" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu39 \
        -takefocus {} -text Browse 
    vTcl:DefineAlias "$site_5_0.tBu39" "browseTButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa37 \
        -in $site_5_0 -x 20 -y 10 -relwidth 0.07 -relheight 0.5 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tex38 \
        -in $site_5_0 -x 60 -y 10 -rely 0.03 -relwidth 0.7 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    place $site_5_0.tBu39 \
        -in $site_5_0 -x 430 -y 10 -rely 0.03 -relheight 0.5 -anchor nw \
        -bordermode ignore 
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr40 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.scr40" "imgTxtScrolled" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr40.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_0.fra39 \
        -in $site_4_0 -x 30 -y 30 -relwidth 0.9 -relheight 0.25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.scr40 \
        -in $site_4_0 -x 30 -y 80 -rely 0.03 -relwidth 0.9 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    $top.tPa37 add $top.tPa37.p1 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa37.p2 \
        -text {Search Image} -underline 7 -width 200 -height 0 
    vTcl:DefineAlias "$top.tPa37.p2" "imageSearchTPane" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa37.p2
    frame $site_4_1.fra41 \
        -borderwidth 5 -relief groove -background {#d9d9d9} -height 75 \
        -width 125 
    vTcl:DefineAlias "$site_4_1.fra41" "getImgFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.fra41
    ttk::label $site_5_0.tLa42 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Enter Text:} 
    vTcl:DefineAlias "$site_5_0.tLa42" "typeTLabel" vTcl:WidgetProc "Toplevel1" 1
    text $site_5_0.tex43 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 10 \
        -wrap word 
    .top37.tPa37.p2.fra41.tex43 configure -font TkTextFont
    .top37.tPa37.p2.fra41.tex43 insert end text
    vTcl:DefineAlias "$site_5_0.tex43" "getText" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_5_0.tBu44 \
        -takefocus {} -text Search 
    vTcl:DefineAlias "$site_5_0.tBu44" "searchTButton" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa42 \
        -in $site_5_0 -x 20 -y 10 -rely 0.07 -relwidth 0.13 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    place $site_5_0.tex43 \
        -in $site_5_0 -x 100 -y 10 -rely 0.07 -relwidth 0.63 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    place $site_5_0.tBu44 \
        -in $site_5_0 -x 440 -y 10 -rely 0.07 -relwidth 0.14 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_1.scr45 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_1.scr45" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_4_1.scr45.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_4_1.fra41 \
        -in $site_4_1 -x 30 -y 30 -relwidth 0.9 -relheight 0.17 -anchor nw \
        -bordermode ignore 
    place $site_4_1.scr45 \
        -in $site_4_1 -x 30 -y 100 -rely 0.07 -relwidth 0.9 -relheight 0.63 \
        -anchor nw -bordermode ignore 
    $top.tPa37 add $top.tPa37.p2 
        
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa37 \
        -in $top -x 10 -y 10 -relwidth 0.97 -relheight 0.97 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

